name: backend-staging-build-and-deploy
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: cd backend && npm i -g yarn && yarn install
      - name: Build
        env:
          STAGING_BACKEND_ENV: ${{ secrets.STAGING_BACKEND_ENV }}
        run: cd backend && yarn build && echo "$STAGING_BACKEND_ENV" > .env
      - name: Copy built files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.STAGING_BACKEND_HOSTNAME }}
          username: ${{ secrets.STAGING_BACKEND_USERNAME }}
          key: ${{ secrets.STAGING_BACKEND_SSH_KEY }}
          source: "backend/"
          target: "/home/ubuntu/strike-staging"
          port: 22
          overwrite: true
      - name: Restart server
        env:
          STAGING_BACKEND_HOSTNAME: ${{ secrets.STAGING_BACKEND_HOSTNAME }}
          STAGING_BACKEND_USERNAME: ${{ secrets.STAGING_BACKEND_USERNAME }}
          STAGING_BACKEND_SSH_KEY: ${{ secrets.STAGING_BACKEND_SSH_KEY }}
        run: |
          echo "$STAGING_BACKEND_SSH_KEY" > private_key && chmod 400 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${STAGING_BACKEND_USERNAME}@${STAGING_BACKEND_HOSTNAME} '
            cd /home/ubuntu/strike-staging/backend &&
            /home/ubuntu/.nvm/versions/node/v16.19.1/bin/pm2 kill &&
            /home/ubuntu/.nvm/versions/node/v16.19.1/bin/pm2 start dist/main.js --name strike-staging-backend
          '
