name: Backend staging

on:
  push:
    branches:
      - develop
      - 20-add-integration-deployment-for-staging

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install yarn
        run: |
          npm install -g yarn
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v2
      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build the project
        run: |
          cp .env.production .env
          npm i -g yarn
          yarn
          yarn build
      - name: Copy the built files over
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.STAGING_HOSTNAME }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.STAGING_PRIVATE_KEY }}
          port: 22
          source: "backend/*"
          target: "/home/ubuntu/Backend"
          overwrite: true
      - name: Restart pm2 for backend services
        env:
          PRIVATE_KEY: ${{ secrets.STAGING_PRIVATE_KEY }}
          USER: ${{ secrets.STAGING_USER }}
          HOSTNAME: ${{ secrets.STAGING_HOSTNAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 400 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOSTNAME} '
            cd /home/ubuntu/Backend/backend &&
            /home/ubuntu/.nvm/versions/node/v16.14.2/bin/pm2 restart Backend
          '
